# Setup
title:        "Parker's Notes"
tagline:      "built with 85 Coffee"
baseurl:      "https://parkerwy.github.io"
paginate:     1

# About/contact
author:
  name:       Parker
  url:        

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
