# Setup
title:        "In Code We Trust"
tagline:      
baseurl:      "https://parkerwy.github.io"
paginate:     1

# About/contact
author:
  name:       Parker
  url:        

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
